# Dependabot configuration
version: 2
updates:
  # Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "⬆ "
      prefix-development: "⬆ [dev] "
    versioning-strategy: "increase-if-necessary"
    groups:
      # Group patch updates to production dependencies
      python-prod:
        dependency-type: "production"
        update-types:
          - "patch"
      # Group minor and patch updates to development dependencies
      python-dev:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "⬆ "
    groups:
      # Group updates to upload/download artifact actions
      gha-artifact:
        patterns:
          - actions/*-artifact
