"""Pytest to read sequence."""

from vhip.mlmodel.read_sequence import read_headers, read_sequence

seq = """AGTACTTGTTGATGCTGATGCACTAGTTGATTCAGATGTGCTCGTACTTGTTGATTCAGACGCACTTGTG
CTCGCTGAAGTACTATTAGATGTAGACGTGCTTGCGCTTATCGATTCAGAAGTACTTGTACTTTCTGAAC
TACTCTCTGAAGTCGAATTACTTAATGAAGTACTTTCACTATTTTTATCTCTTGCTGATTCGCTTTCTGA
TAATGATGCACTGTTTACTGAATTACTCGTTGAAGTACTTGCTGATTGTAAACGAGATAGTGAATCACTG
ATTGATGCACTTTCTGATTCGATTTTTTCTGTTGATTCACTTTCTGAATTACTCGATGAAGCACTTAATG
ATTCACTTTCGAATACTGAATCTTCTAATGAATTAGAAATACTAATCGAATCTTGATTACTTTTACGTTG
TGATTCACTCTTCGATAACGACTCATTATTTGAATCTCTTACTGATTCACTCTTCGATAAAGATGCACTA
TTTTCTGAGGCACGTTTTGAATCAGATTCACTTAGACTTTTGGTTCTTGAAGCATCTTCTGAAGCTATCT
CTGAATTTGCTTTGCTTATAGACGTTGATCTTGATGCATCTTCTGAAGCTCTTTCTGAATTTACTTTGCT
TATAGACGCTGATCTTGATGCATCTTCAGAAGCTATTTCTGAATTTACTTTGCTTATAGATGCTGACCTT
GAAGCTTCTTGTGAGTTTCTCACTGAATCTGAGTTAGCTGTACTTTCTGATCTTGATTTCTCTTCAGAAA
GTCGTGAGTCTTCTGATCTACTATTACTTTCAGATGCACGTACAACACTTTCAGATGCTTTTTTAGAATT
GCTCTCTTGTTCTGAAAGTCGCTTAGAATTACTTTGTTGCTCTGAAAGTCGCTTAGAATTACTTTGTTGC
TCTGAAAGTCGCTTAGAATTACTTTGTTGCTCTGAAAGTCGCTTAGAATTACTTTGTTGCTCTGAAAGTC
GCTTAGAAGTGCTTGCTTGCTCTGAAAGACGTTTAGAATTACTTTGTTGTTCTGAAGCTTTCTTAGAAGT
GCTTTGTTGTTCAGAGGCTCTCGATTGACTTTGAGAATCCGCAATACTTTGGCTTGCAGATTTCGATGCA
ACAGATGGGTCTTCACCATGAATTACTGGTGCAGCGCCACCACGGCCTATAAAGAAGTTTCTATTTGAAT
CTGTGGAACTCGCAAATGGAACAAAGTCCCAAGTTGCATTATCAGCTATAATATTTGCGCTCCATTTTGT"""

cleaned_seq = seq.replace("\n", "")  # remove \n created by long string


def test_read_sequence():
    """Test to check if reading fasta file is working as intended."""
    # test 1 - check length of sequences match
    filename = "tests/datatests/test_sequence.fasta"
    res = read_sequence(filename)
    assert len(res[0]) == len(cleaned_seq)

    # test 2 - check that sequences do match
    assert res[0] == cleaned_seq


def test_read_headers():
    """Test to read header of a fasta file."""
    headers = ["NZ_CP065712.1"]
    filename = "tests/datatests/test_sequence.fasta"
    res = read_headers(filename)
    assert res == headers


def test_read_sequence_many_contigs():
    """Test to read a fasta file with many contigs."""
    filename = "tests/datatests/test_sequence_multiple_contigs.fasta"
    res = read_sequence(filename)
    assert len(res) == 2
